"""Scaffold generators for plugins (SDK Developer Platform)."""
from __future__ import annotations

from pathlib import Path

COMPONENT_TYPES = ("provider", "capability", "adapter", "consumer", "ruleset")


def create_component(
    kind: str,
    name: str,
    *,
    root: Path | None = None,
    author: str = "community",
) -> Path:
    kind = kind.strip().lower()
    name = _slug(name)
    if kind not in COMPONENT_TYPES:
        raise ValueError(f"kind inválido: {kind}. Use: {COMPONENT_TYPES}")
    root = root or (Path.cwd() / "plugins")
    plugin_dir = root / name
    if plugin_dir.exists():
        raise FileExistsError(f"já existe: {plugin_dir}")
    plugin_dir.mkdir(parents=True)

    module_file = {
        "provider": "provider.py",
        "capability": "capability.py",
        "adapter": "adapter.py",
        "consumer": "consumer.py",
        "ruleset": "ruleset.py",
    }[kind]
    class_name = {
        "provider": f"{_pascal(name)}Provider",
        "capability": f"{_pascal(name)}Capability",
        "adapter": f"{_pascal(name)}Adapter",
        "consumer": f"{_pascal(name)}Consumer",
        "ruleset": f"{_pascal(name)}Ruleset",
    }[kind]

    (plugin_dir / "__init__.py").write_text(
        f'"""Plugin {name} — generated by signalhub create."""\n',
        encoding="utf-8",
    )
    (plugin_dir / module_file).write_text(
        _template(kind, name, class_name),
        encoding="utf-8",
    )
    manifest_key = {
        "provider": "providers",
        "capability": "capabilities",
        "adapter": "adapters",
        "consumer": "consumers",
        "ruleset": "rulesets",
    }[kind]
    # module path when plugins/<name> is on sys.path: import <name>.provider
    mod = f"{name}.{module_file[:-3]}"
    yaml = f"""# SignalHub plugin manifest — do not edit Core; extend via plugins.
name: {name}
version: 0.1.0
author: "{author}"
description: "Scaffold {kind} plugin ({name})"
signalhub_version: ">=0.2.0"
permissions:
  - none
{manifest_key}:
  - module: {mod}
    class: {class_name}
"""
    (plugin_dir / "plugin.yaml").write_text(yaml, encoding="utf-8")
    (plugin_dir / "README.md").write_text(
        f"# Plugin `{name}`\n\nGenerated `{kind}` scaffold. See docs/developers/.\n",
        encoding="utf-8",
    )
    return plugin_dir


def _slug(name: str) -> str:
    s = "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in name.strip().lower())
    s = s.replace("-", "_")
    if not s or not s[0].isalpha():
        raise ValueError("nome deve começar com letra")
    return s


def _pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_") if part)


def _template(kind: str, name: str, class_name: str) -> str:
    if kind == "provider":
        return f'''\
from __future__ import annotations

from typing import Sequence

from signalhub.core.contracts.provider import ProviderQuery, RawHit
from signalhub.sdk import ProviderPlugin


class {class_name}(ProviderPlugin):
    """Example Provider — returns empty until wired to a public source (ToS-aware)."""

    provider_id = "{name}"
    provider_name = "{_pascal(name)}"
    description = "Scaffold provider — SignalHub framework extension (not a scraper core)."
    capability_ids = ("discover_signals",)

    def search(self, query: ProviderQuery) -> Sequence[RawHit]:
        _ = query
        # Explicit empty — never invent Signals.
        return ()
'''
    if kind == "capability":
        return f'''\
from __future__ import annotations

from typing import Any, Mapping

from signalhub.sdk import Capability, CapabilityPlugin, CapabilityResult


class {class_name}(CapabilityPlugin):
    def capability(self) -> Capability:
        return Capability(
            id="{name}",
            name="{_pascal(name)}",
            description="Scaffold capability — consumes Signals only (no mutation).",
            input_schema={{"type": "object", "properties": {{"limit": {{"type": "integer"}}}}}},
            mcp_tool_name="{name}",
        )

    def execute(self, arguments: Mapping[str, Any]) -> CapabilityResult:
        _ = arguments
        return CapabilityResult(
            capability_id="{name}",
            status="ok_stub",
            items=[],
            meta={{"ai": False, "plugin": "{name}"}},
        )
'''
    if kind == "adapter":
        return f'''\
from __future__ import annotations

from typing import Any, Mapping, Sequence

from signalhub.core.models import Signal
from signalhub.sdk import NotificationAdapterPort


class {class_name}(NotificationAdapterPort):
    def adapter_id(self) -> str:
        return "{name}"

    def notify(self, signals: Sequence[Signal]) -> Mapping[str, Any]:
        return {{
            "adapter": "{name}",
            "count": len(signals),
            "status": "ok_stub",
            "nota": "Adapter scaffold — wire Discord/Slack/etc. without touching Core.",
        }}
'''
    if kind == "consumer":
        return f'''\
from __future__ import annotations

from typing import Any, Mapping, Sequence

from signalhub.core.models import Signal
from signalhub.sdk import SignalConsumer


class {class_name}(SignalConsumer):
    def consumer_id(self) -> str:
        return "{name}"

    def consume(self, signals: Sequence[Signal]) -> Mapping[str, Any]:
        return {{
            "consumer": "{name}",
            "count": len(signals),
            "status": "ok_stub",
            "nota": "Consumer scaffold — CRM/webhook/email sink.",
        }}
'''
    # ruleset
    return f'''\
from __future__ import annotations

from typing import Sequence

from signalhub.rules import KeywordCategoryRule, Rule
from signalhub.sdk import RulesetPlugin


class {class_name}(RulesetPlugin):
    def ruleset_id(self) -> str:
        return "{name}"

    def rules(self) -> Sequence[Rule]:
        return [
            KeywordCategoryRule(
                mapping={{
                    # Customize for your vertical — explanations feed Telegram/MCP.
                    "exemplo": ("other", 1.0),
                }}
            )
        ]
'''
